- hosts: agent

  tasks:
    - name: Create docker cert directory
      file:
        path: /etc/docker/certs.d/master.mesos:5000
        state: directory
        mode: 0755 
      become: yes

    - name: Download docker certificate
      get_url:
        url: http://master.mesos:8082/certs/domain.crt
        dest: /etc/docker/certs.d/master.mesos:5000/ca.crt
      become: yes
       
    - name: Restart docker
      systemd: state=restarted name=docker
      become: yes

    - name: Create UCR directory
      file:
        path: /var/lib/dcos/pki/tls/certs
        state: directory

    - name: Copy UCR certificate
      copy:
        src: /etc/docker/certs.d/master.mesos:5000/ca.crt
        dest: /var/lib/dcos/pki/tls/certs/ca.crt
        remote_src: yes
      become: yes

    - name: Check certificate hash
      command: "openssl x509 -hash -noout -in ca.crt"
      args:
        chdir: /var/lib/dcos/pki/tls/certs/
      register: key

    - name: Create a softlink
      file:
        src: /var/lib/dcos/pki/tls/certs/ca.crt
        dest: /var/lib/dcos/pki/tls/certs/{{ key.stdout }}.0
        state: link
      become: yes

